### ISSUE TITLE
Empty structure for sdmxthon.model.definitions.DataFlowDefinition

### ISSUE THREAD

**Issue by osirello** [Meaningful-Data/sdmxthon#40]
Running the following code returns a `NoneType`. Is this expected?

```
import sdmxthon

url = "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/dataflow/ESTAT/MET_EDAT_LFSE4/1.0?detail=full"

message = sdmxthon.read_sdmx(url)
resource = message.payload[list(message.payload)[0]]
df = resource[list(resource)[0]]

df.structure
```
I would expect it returns `<s:Structure>`, for example:
`<Ref id="MET_EDAT_LFSE4" version="18.0" agencyID="ESTAT" package="datastructure" class="DataStructure"/>`

Is this correct or is there another way to handle it?

Thank you very much in advance.

**Comment by antonio-olleros** [comment]
Hi!

Actually, the issue is that, in your query, you are not getting the descendants, so, if you check the sdmx file you get, there is no DSD. The read_sdmx method reads what it gets, it does not look for the descendants itself.
I normally use the references parameter in the query with all or descendats value. Eurostat's  API does not implement the all option. If you run the following script:

`    url = "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/dataflow/ESTAT/MET_EDAT_LFSE4/1.0?detail=full&references=descendants"

    message = read_sdmx(url)
    dataflow = list(message.payload['Dataflows'].values())[0]
    print(dataflow.structure)`

You'll get the structure

**Comment by osirello** [comment]
Dear @antonio-olleros , thank you very much. Indeed, you are absolutely correct - it works.
Thank you again for this library.
